# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './design.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(985, 794)
        Dialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        Dialog.setStyleSheet("m")
        self.button = QtWidgets.QPushButton(Dialog)
        self.button.setGeometry(QtCore.QRect(30, 30, 921, 51))
        self.button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button.setStyleSheet("font-size: 20px;")
        self.button.setObjectName("button")
        self.sex_button = QtWidgets.QPushButton(Dialog)
        self.sex_button.setGeometry(QtCore.QRect(780, 110, 171, 61))
        self.sex_button.setObjectName("sex_button")
        self.age_button = QtWidgets.QPushButton(Dialog)
        self.age_button.setGeometry(QtCore.QRect(780, 200, 171, 61))
        self.age_button.setObjectName("age_button")
        self.personal_button = QtWidgets.QPushButton(Dialog)
        self.personal_button.setGeometry(QtCore.QRect(780, 290, 171, 61))
        self.personal_button.setObjectName("personal_button")
        self.education_button = QtWidgets.QPushButton(Dialog)
        self.education_button.setGeometry(QtCore.QRect(780, 380, 171, 61))
        self.education_button.setObjectName("education_button")
        self.graphic_label = QtWidgets.QLabel(Dialog)
        self.graphic_label.setGeometry(QtCore.QRect(30, 100, 731, 661))
        self.graphic_label.setStyleSheet("background-color: white;\n"
"")
        self.graphic_label.setText("")
        self.graphic_label.setObjectName("graphic_label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.button.setText(_translate("Dialog", "Выбрать CSV файл"))
        self.sex_button.setText(_translate("Dialog", "Пол"))
        self.age_button.setText(_translate("Dialog", "Возраст"))
        self.personal_button.setText(_translate("Dialog", "Приоритеты"))
        self.education_button.setText(_translate("Dialog", "Образование"))
